In [1]:
from tensorflow.keras.preprocessing.text import one_hot


In [2]:
### sentences
sent = ['the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        ' I am a good developer',
        'understand the meaning of words',
        'your videos are good']

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 ' I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size = 10000

In [6]:
### One Hot Representation
one_hot_repr = [one_hot(words,voc_size) for words in sent]
one_hot_repr

[[930, 2429, 7597, 7863],
 [930, 2429, 7597, 8321],
 [930, 8468, 7597, 2130],
 [2198, 7940, 7686, 5544, 828],
 [2198, 7940, 7686, 5544, 3363],
 [2588, 930, 9190, 7597, 7164],
 [2318, 2815, 3072, 5544]]

In [8]:
## Word Embedding Representation

from tensorflow.keras.layers import Embedding 
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np


In [9]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0  930 2429 7597 7863]
 [   0    0    0    0  930 2429 7597 8321]
 [   0    0    0    0  930 8468 7597 2130]
 [   0    0    0 2198 7940 7686 5544  828]
 [   0    0    0 2198 7940 7686 5544 3363]
 [   0    0    0 2588  930 9190 7597 7164]
 [   0    0    0    0 2318 2815 3072 5544]]


In [10]:
## Feature Represantation
dim = 10

In [12]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [13]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [14]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 240ms/step


array([[[ 0.04887338,  0.00593141,  0.03215629,  0.03374498,
         -0.01489007,  0.01972054, -0.02227647, -0.02662877,
         -0.04886966,  0.04494324],
        [ 0.04887338,  0.00593141,  0.03215629,  0.03374498,
         -0.01489007,  0.01972054, -0.02227647, -0.02662877,
         -0.04886966,  0.04494324],
        [ 0.04887338,  0.00593141,  0.03215629,  0.03374498,
         -0.01489007,  0.01972054, -0.02227647, -0.02662877,
         -0.04886966,  0.04494324],
        [ 0.04887338,  0.00593141,  0.03215629,  0.03374498,
         -0.01489007,  0.01972054, -0.02227647, -0.02662877,
         -0.04886966,  0.04494324],
        [ 0.02223775, -0.01896232,  0.02713741, -0.01889645,
          0.03564775, -0.0440696 ,  0.00599293, -0.04231262,
         -0.02159449, -0.03993592],
        [-0.01992686,  0.02921707,  0.01077738,  0.01358188,
          0.02298713,  0.04242455, -0.03941966, -0.01612805,
         -0.01409112, -0.00856077],
        [-0.0120541 ,  0.00852904,  0.02881876, -0.0

In [18]:
model.predict(embedded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None
  • kwargs=<class 'inspect._empty'>